-- `collect-data`.boss_job_details definition

CREATE TABLE `boss_job_details` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `encrypt_job_id` varchar(500) NOT NULL COMMENT '职位加密ID (唯一索引)',
  `job_name` varchar(255) NOT NULL COMMENT '职位名称',
  `salary_desc` varchar(100) DEFAULT NULL COMMENT '薪资描述',
  `city_name` varchar(50) DEFAULT NULL COMMENT '城市',
  `area_district` varchar(50) DEFAULT NULL COMMENT '行政区',
  `business_district` varchar(50) DEFAULT NULL COMMENT '商圈',
  `job_degree` varchar(50) DEFAULT NULL COMMENT '学历要求',
  `job_experience` varchar(50) DEFAULT NULL COMMENT '经验要求',
  `encrypt_brand_id` varchar(64) DEFAULT NULL COMMENT '公司加密ID',
  `brand_name` varchar(255) DEFAULT NULL COMMENT '公司名称',
  `brand_logo` varchar(500) DEFAULT NULL COMMENT '公司Logo链接',
  `brand_stage_name` varchar(50) DEFAULT NULL COMMENT '融资阶段',
  `brand_industry` varchar(100) DEFAULT NULL COMMENT '行业',
  `brand_scale_name` varchar(100) DEFAULT NULL COMMENT '公司规模',
  `encrypt_boss_id` varchar(64) DEFAULT NULL COMMENT '招聘者加密ID',
  `boss_name` varchar(100) DEFAULT NULL COMMENT '招聘者姓名',
  `boss_title` varchar(100) DEFAULT NULL COMMENT '招聘者职位',
  `boss_avatar` varchar(500) DEFAULT NULL COMMENT '招聘者头像',
  `boss_cert` int DEFAULT NULL COMMENT '认证状态',
  `skills` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '技能标签列表',
  `welfare_list` varchar(500) DEFAULT NULL COMMENT '福利列表',
  `job_labels` varchar(500) DEFAULT NULL COMMENT '职位通用标签',
  `gps_location` point DEFAULT NULL COMMENT '地理位置坐标 (MySQL空间类型)',
  `security_id` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '安全ID',
  `lid` varchar(100) DEFAULT NULL COMMENT '列表ID',
  `created_time` date DEFAULT (curdate()) COMMENT '抓取时间',
  `boss_online` tinyint(1) DEFAULT NULL COMMENT '是否在线',
  `updated_time` date DEFAULT (curdate()),
  PRIMARY KEY (`id`),
  UNIQUE KEY `boss_job_details_encrypt_job_id_IDX` (`encrypt_job_id`,`created_time`) USING BTREE,
  KEY `idx_brand_id` (`encrypt_brand_id`),
  KEY `idx_city` (`city_name`)
) ENGINE=InnoDB AUTO_INCREMENT=1801 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Boss直聘职位详情表';